# Generated by Django 5.2.4 on 2025-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="goals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
