# Generated by Django 5.2.4 on 2025-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_profilemodel_address_profilemodel_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemodel",
            name="goals",
        ),
    ]
